### ISSUE TITLE
Relicensing to LGPL-2.1-or-later from LGPL-2.1-only

### ISSUE THREAD

**Issue by abetomo** [groonga/groonga-nginx#12]
We plan to relicense Groonga to LGPL-2.1-or-later.
https://github.com/groonga/groonga/issues/1774
See that issue for why.

groonga-nginx will be relicensed to LGPL-2.1-or-later according to Groonga.

**Comment by abetomo** [comment]
This repository was separated from Groonga.
Separated from `src/httpd` by https://github.com/groonga/groonga/commit/ae00cf3e2b9c77d9d478161d691e322863e5b887 commit.

In the Groonga repository, here are the authors of the patches:

```
$ git checkout 'ae00cf3e2b9c77d9d478161d691e322863e5b887^'
$ git shortlog -sn src/httpd
    99  Kouhei Sutou
    11  Kentaro Hayashi
     9  HAYASHI Kentaro
     5  Sutou Kouhei
     4  Motoi Washida
     1  Takashi Hashida
```

The GitHub account is as follows:

* @kou
* @kenhys
* @wm3
* @HashidaTKS

For commits in the Groonga repository, we have these authors agree to the license change at https://github.com/groonga/groonga/issues/1774.

**Comment by kenhys** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by kou** [comment]
We don't need to additional agreements for commits in groonga/groonga but we have additional commits in groonga/groonga-nginx:

```console
$ git shortlog -sn | cat
    44	Sutou Kouhei
     5	dependabot[bot]
     2	Abe Tomoaki
     1	takuya kodama
```

We need additional agreements for them.

**Comment by abetomo** [comment]
I'm sorry for the confusion.
No additional agreement is needed for groonga/groonga commits.
We need to have agreement from the groonga/groonga-nginx patch authors.

Here are authors:

* [ ] @kou
* [ ] @abetomo
* [ ] @otegami

(This includes trivial patch authors, but since it is a small group, we will list them all.)

If you agree with the relicensing, could you comment the following on this issue.

> I agree to apply LGPL-2.1-or-later to my commits.

**Comment by kou** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by abetomo** [comment]
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by otegami** [comment]
Thank you for dealing with it.
I agree to apply LGPL-2.1-or-later to my commits.

**Comment by abetomo** [comment]
Thanks for the confirmation.
All agreed, we will change the license.
Update the license file in the repository and the license header in each file.

**Comment by abetomo** [comment]
No license file update is needed.
https://github.com/groonga/groonga-nginx/blob/main/COPYING
https://spdx.org/licenses/LGPL-2.1-or-later.html

Update the license header of each file.

**Comment by kou** [comment]
Ah, we need to update https://github.com/groonga/groonga-nginx/blob/main/packages/debian/copyright too.

**Comment by kou** [comment]
https://github.com/groonga/groonga-nginx/blob/657a201f7179ee6f4d68c9560da3756c67acc71e/packages/debian/copyright#L8-L10

**Comment by kou** [comment]
* https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-field
* https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-specification
